### ISSUE TITLE
MetalWorksDesktopThemeWithAssetManager initialization

### ISSUE THREAD

**Issue by b005t3r** [joshtynjala/feathers#1067]
Two things can be fixed to make using this theme more straightforward:
assetPaths declaration:
```as3
		protected var assetPaths:Vector.<String> = new <String>
			[
				ATLAS_NAME + ".xml",
				ATLAS_NAME + ".png"
			];
```

and constructor's default params:
```as3
		public function MetalWorksDesktopThemeWithAssetManager(assetsBasePath:String = "images", assetManager:AssetManager = null)
		{
			this.loadAssets(assetsBasePath, assetManager);
		}
```

Currently it crashes when using default params and it's really hard to use, when you enter a custom path (it looks for subdirectory "images" there which, when using the default theme directories - by e.g. settings Sources Root to "assets" - doesn't exist).

**Comment by joshtynjala** [comment]
Yes, I see that the themes that use the AssetManager can be cleaned up a little bit.

> assetPaths declaration:

Using the ATLAS_NAME constant in the assetPaths variable is a good idea.

I plan to keep the "images/" part in there though. Some of the example themes have assets in more subdirectories than "images". That's why it expects the parent directory. The example themes should be consistent, so even though this particular theme only has files in "assets/images", it's better to keep it in line with the other example themes that have more subdirectories in "assets". MinimalDesktopThemeWithAssetManager is one theme that has more than one subdirectory in "assets", and it loads the following files:

* "images/minimal_mobile.xml",
* "images/minimal_mobile.png",
* "fonts/pf_ronda_seven.fnt"

It has both "images" and "fonts".

> and constructor's default params:
> Currently it crashes when using default params and it's really hard to use, when you enter a custom path (it looks for subdirectory "images" there which, when using the default theme directories - by e.g. settings Sources Root to "assets" - doesn't exist). 

Ah yes, I see that the assetsBasePath parameter defaults to null, and it results in a runtime error. When I change it to point to "./", and I add "assets" to the source path in Flash Builder, it works right away. I'll make sure that it defaults to "./" instead.
