### ISSUE TITLE
Scroller: the current page index is sometimes calculated incorrectly

### ISSUE THREAD

**Issue by harry248** [joshtynjala/feathers#1081]
I am doing something like this:

_list.itemRendererProperties.width = actualWidth;
_list.itemRendererProperties.height = actualHeight;
_list.pageWidth = actualWidth;
_list.pageHeight = actualHeight;
_list.setSize(actualWidth, actualHeight);

Layout is a HorizontalLayout with snapToPages set to true. My data provider has 3 items. Scrolling to the first or last item the horizontalPageIndex is correct but for the second it equals 0. I had to change the Math.floor() call in line 3893 of refreshPageIndices() to Math.round() to fix it.

**Comment by joshtynjala** [comment]
Math.round() won't work in refreshPageIndices(), unfortunately. It will become the opposite problem. Instead of reporting the previous page instead of the current page, it will report the next page. Even worse, it will happen more frequently.

What we're seeing here is probably a floating point math error. The scroll position is probably off by less than 1 pixel. I have workarounds for that type of issue throughout Feathers, so it shouldn't be too difficult to fix. However, since I don't want to accidentally introduce a bug just as I'm about to release the stable build of 2.1, it'll have to wait a short time.

**Comment by harry248** [comment]
No problem! Thanks for taking care.

**Comment by joep1978** [comment]
I'm seeing a similar issue using the SpinnerList - the vertical page index is sometimes wrong if I use a BitmapFontTextRenderer for the item label.

However using Math.round() in refreshPageIndices does seem to solve it for me.

**Comment by joshtynjala** [comment]
The problem with Math.round() is when you are dragging. The page index will be updated way too early before you reach the next page. In some cases, that might not matter, but it's very important at other times.
