### ISSUE TITLE
Clipped text issue when embedFonts is enabled

### ISSUE THREAD

**Issue by mumeka** [joshtynjala/feathers#1095]
I was using 2.1.0.Beta and everything was ok. However when i started to use 2.1.0 texts started to become blurred and clipped. Commit https://github.com/joshtynjala/feathers/commit/8fb0d2a34caaaf8598e26698f07d82243fde03dc fixes blurring issue. However clipping issue still there.

I embed Arial font with

	[Embed(source="/fonts/arial.ttf", embedAsCFF="false", fontFamily="Arial")]
	public static const Arial:Class;

Than use like that:

	public static function labelFunctionArialTextFormatter(fontSize:Number, color:uint, align:String=null, leading:Number=5, wordWrap=false):ITextRenderer
	{
			var textRenderer:TextFieldTextRenderer = new TextFieldTextRenderer();
			textRenderer.textFormat = new TextFormat( "Arial", fontSize, color, null, null, null, null, null, align, null, null, null, leading);
			textRenderer.embedFonts = true;
			textRenderer.wordWrap = wordWrap;
			textRenderer.snapToPixels = true;
			textRenderer.isHTML = true;
			
			return textRenderer;
	}

In the above function if i set embedFonts to false at 2.1.0 than clipping does not happen.

This same code does not create clipping at 2.1.0.beta so commit https://github.com/joshtynjala/feathers/commit/43234c3591f0672f362bfd6553eff819cb5bba76 seems to started issue.

I reverted TextFieldTextRenderer class to https://github.com/joshtynjala/feathers/blob/1cce397b8235c75724f0819195a0e3829a65fa6a/source/feathers/controls/text/TextFieldTextRenderer.as in my codebase and clipping issue fixed.

Screenshot:

![clipping](https://cloud.githubusercontent.com/assets/3039771/6513963/a93c80cc-c387-11e4-8775-1fe816abb671.png)

**Comment by joshtynjala** [comment]
I fixed this issue in commit 8fb0d2a34caaaf8598e26698f07d82243fde03dc about a week ago.

A 2.1.1 update is on the way soon.

**Comment by mumeka** [comment]
I already told in my explanation blurring is already fixed, however clipping is not fixed. Can you read my text?

**Comment by joshtynjala** [comment]
Sorry about that. 

I am not able to reproduce a difference between 2.0.1 and the latest source code. I know that you mentioned 2.1.0 beta, but a difference between stable versions is the key factor here. It's likely that the behavior in 2.1.0 was actually caused by a bug that was fixed before the stable 2.1.0.

The clipping is actually caused by the useGutter property added in Feathers 2.0.0. The class flash.text.TextField adds a 2 pixel gutter around all edges of its text, and Feathers corrects for that so that TextFieldTextRenderer will align better when positioned next to other text renderers. Unfortunately, it seems that TextField sometimes renders part of its text outside of the textWidth and textHeight that it reports, so sometimes it gets clipped when useGutter is false. You can set useGutter to true to work around this issue.

**Comment by mumeka** [comment]
Thank you for explanation Josh.

I will try useGutter property,
Have a nice day.

**Comment by joshtynjala** [comment]
I gave it another look, and I discovered that I could improve the clipping while keeping useGutter set to false. In cases where the text measured in partial pixels (like 62.8), it rounded down to the nearest pixel (62.8 becomes 62) when it should have rounded up (it should have become 63).

I plan to save this fix for 2.2.0 instead of releasing it in 2.1.1 because even though it is a simple change, it may affect layout and measurement in existing apps.

**Comment by mumeka** [comment]
It is nice to hear it can be improved like that :clap:. I am going to use https://github.com/joshtynjala/feathers/commit/e4fb244f5ced3782483f5be14d21a7e79ec1ac68 immediately, because my app doesn't use automated layout sizing a lot, so it will not have negative impact on my app.
