### ISSUE TITLE
PopUp Crashes on iOS on stage resize (while device orientation changes)

### ISSUE THREAD

**Issue by mariommoreno** [joshtynjala/feathers#1143]
When resize event is dispatched, width and height are not updated yet (switched due to rotation).

- Centering/resize is failing for overlay and centered elements
- In some cases an exception is launched by VerticalLayout (index out of bounds in "validateItems") 

Tested with Air 18 beta with iOS7 & iOS8

**Comment by joshtynjala** [comment]
Can you put together a simple class that will reproduce the issue?

**Comment by mariommoreno** [comment]
We can reproduce the resize issue with: 
```PopUpManager.addPopUp(new Quad(300,300,0xFF0000), true, true)```
After a single rotation, Quad doesn't appear centered.

The "out of bounds" error seems to be a collision between this issue and the rendering optimization of a list with verticalLayout.

If resize issue is solved, probably the second issue won't occur.

**Comment by joshtynjala** [comment]
I had trouble reproducing this issue at first. Adding a Quad as a pop-up was working correctly for me. I could rotate as much as I wanted without issue.

In your code to initialize Starling, you probably listen for when the native stage resizes so that you can adjust the dimensions of the Starling view port and the Starling stage. A while back, I found that you need to give this listener a higher priority so that it is called before Starling dispatches its own stage resize event.

    stage.addEventListener(Event.RESIZE, stage_resizeHandler, false, int.MAX_VALUE, true);

If it has the default priority of 0, Starling will dispatch its own stage resize event first, but the stage size will not have been updated yet.

**Comment by mariommoreno** [comment]
Thank you!
You were right, it was a priority problem but curiously only popups where
affected.

Thanks again!


_____________________

*Mario Morales Moreno*
 Tel. (+34) 678 43 73 72
