### ISSUE TITLE
Scroller::stopScrolling() blocks future scrolling

### ISSUE THREAD

**Issue by ZwickTheGreat** [joshtynjala/feathers#1159]
_touchPointID should be set to -1 in stopScrolling() function

**Comment by joshtynjala** [comment]
This is by design. Scrolling is stopped until the current touch ends. _touchPointID is set to -1 in stage_touchHandler() on the ended phase.

**Comment by ZwickTheGreat** [comment]
What if the touchEvent's propagation is stopped by another listener? The Scroller is locked.

**Comment by ZwickTheGreat** [comment]
Btw. the worst behaviour is on iOS, when every single touch has it's own specific touch id.

**Comment by joshtynjala** [comment]
Stopping propagation after TouchPhase.BEGAN for any event listener that handles both TouchPhase.BEGAN and TouchPhase.ENDED is probably going to break something. That's an issue that goes beyond Scroller and stopScrolling().

Since stopScrolling() isn't meant to clear the saved touch ID, I recommend subclassing ScrollContainer or List or whichever component that you're using, and add your own custom function that clears the touch ID too. It is protected, so a subclass will have access to it.
