### ISSUE TITLE
TextInput + StageTextTextEditor - Blurry/cut off text

### ISSUE THREAD

**Issue by krausste** [joshtynjala/feathers#945]
We experienced an weird issue with blurry/cut off text in TextInput + StageTextTextEditor when using TextInput->text.
TextInput->prompt is working fine.
The air version is looking blurry, on devices the text is cut off (see screenshots).
We are fading in the view container (scaling). Without this scaling animation everything looks fine. Maybe this issue is related to the function refreshSnapshot()?
![feathers_textinput_blurriness_air](https://cloud.githubusercontent.com/assets/5039360/3749990/6a4ca4ba-17f1-11e4-8ca3-777188e5fd87.png)
![feathers_textinput_blurriness_device](https://cloud.githubusercontent.com/assets/5039360/3749989/6a4c3f70-17f1-11e4-9648-9a2e6e892bf4.png)

**Comment by tonidurans** [comment]
Hey guys!, is there any solution for this issue? , I´m experiencing the same in one project, but I don´t know why in other projects don´t.

Regards!

**Comment by zenrobin** [comment]
We had blurry text at one point. In our case it was caused by adding the
input text box at a small size and then scaling back up to 1.0.  I'm not an
expert, but it seemed as though the tt font used for rasterization was
being sized according to the initial scale, not the final scale.

Lots of ways to work around this, including adding at 1.0 but with alpha 0,
validating, then scaling down for the start point of the animation --that
way you're scaling a big font down instead of a little font up.

Not sure if it's the same issue here, but figured I'd share anyway.

-Robin

**Comment by joshtynjala** [comment]
I was trying to be smart by providing an optimized texture for the scale of the text editor. However, I didn't watch for scale changes, so the texture wasn't recreated. This resulted in very blurry textures when scaled up from a small value to 1.

I added new property named updateSnapshotOnScaleChange to various text renderers and text editors. This property will default to false, which means that the texture snapshot will always be taken as if scaleX and scaleY were 1. This should allow scaling animations that work as expected. However, the text may become a little blurry when scaled up beyond 1.

When updateSnapshotOnScaleChange is set to true, the texture snapshot will be retaken every time that the scale changes. This will keep the text looking crisp at any scale. However, enabling this property may hurt performance because the text renderer or text editor needs to watch for scale changes.
